name: Dependency Check
on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependency-check:
    name: "Dependency Review"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run dependency review
        uses: actions/dependency-review-action@v3
        with:
          config-file: '.github/dependency-review-config.yml'
